# Generated by Django 3.2.15 on 2022-08-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simple_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitperpage",
            name="origin",
            field=models.CharField(default="", max_length=250),
        ),
    ]
