# Generated by Django 4.1.1 on 2022-09-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simple_analytics", "0002_visitperpage_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitperpage",
            name="user_agent",
            field=models.TextField(default=""),
        ),
    ]
