# Generated by Django 4.2.28 on 2026-02-23 10:05
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_analytics", "0003_visitperpage_user_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitperpage",
            name="page",
            field=models.TextField(),
        ),
    ]
