# Generated by Django 4.1.1 on 2025-06-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_analytics', '0003_visitperpage_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitperpage',
            name='page',
            field=models.TextField(),
        ),
    ]
